{{- if and (ne .Values.clusterType "hub") (((((.Values.platform).argocdApps).stakaterReloader).enabled) | default false) }}
{{- $appConfig := ((.Values.platform).argocdApps).stakaterReloader }}
{{- $vars := dict -}}
{{- include "default.variables" (dict "vars" $vars "appConfig" $appConfig "Values" .Values) }}
{{- $repoURL        := default "https://stakater.github.io/stakater-charts" $vars.repoURL -}}
{{- $chart          := default "reloader" $vars.chart -}}
{{- $targetRevision := default "1.0.121" $vars.targetRevision -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stakater-reloader-{{ $vars.clusterName }}
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    platform/chart: reloader
    platform/version: {{ $vars.platformVersion }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ $vars.destinationNamespace }}
    server: https://kubernetes.default.svc
  project: default
  info:
   - name: "Chart repo URL"
     value: "{{ $repoURL }}"
  source:
    helm:
      valuesObject:
        reloader:
          deployment:
            securityContext:
              runAsUser: null
    chart: {{ $chart }}
    repoURL: {{ $repoURL }}
    targetRevision: {{ $targetRevision }}
{{- if $vars.customSyncPolicy }}
  syncPolicy: {{ $vars.customSyncPolicy | toYaml | nindent 4 }}
{{- else if $vars.platformSyncPolicy }}
  syncPolicy: {{ $vars.platformSyncPolicy | toYaml | nindent 4 }}
{{- else }}
  syncPolicy: {}
{{- end }}
{{- end }}
