{{- if ((((.Values.platform).argocdApps).stakaterReloader).enabled | default false) }}
{{- $appConfig := ((.Values.platform).argocdApps).stakaterReloader }}
{{- $repoURL := (default "https://stakater.github.io/stakater-charts" $appConfig.repoURL) }}
{{- $chart := (default false $appConfig.chart) }}
{{- $path := (default false $appConfig.path) }}
{{- $targetRevision := (required "targetRevision missing" $appConfig.targetRevision) }}
{{- $platformSyncPolicy := (default false ((.Values.platform).argocd).syncPolicy) }}
{{- $customSyncPolicy := (default false (($appConfig).syncPolicy)) }}
{{- $platformVersion := (required "platform.version is required" (.Values.platform).version) }}
{{- $clusterType := .Values.clusterType }}
{{- $clusterGroup := .Values.clusterGroup }}
{{- $clusterName := .Values.clusterName }}
{{- $region := .Values.region }}
{{- $owner := .Values.owner }}
{{- $destinationNamespace := (default "platform-tools" ($appConfig.destination).namespace) }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stakater-reloader-{{ $clusterName }}
  namespace: platform-tools
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    platform/chart: reloader
    platform/version: {{ $platformVersion }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ $destinationNamespace }}
    server: https://kubernetes.default.svc
  project: default
  info:
   - name: "Chart Gitlab repo URL"
     value: "{{ $repoURL }}"
  source:
    helm:
      valuesObject:
        reloader:
          deployment:
            securityContext:
              runAsUser: null
    {{- if $path }}
    path: {{ $path }}
    {{- else if $chart }}
    chart: {{ $chart }}
    {{- end }}
    repoURL: {{ $repoURL }}
    targetRevision: {{ $targetRevision }}
{{- if $customSyncPolicy }}
  syncPolicy: {{ $customSyncPolicy | toYaml | nindent 4 }}
{{- else if $platformSyncPolicy }}
  syncPolicy: {{ $platformSyncPolicy | toYaml | nindent 4 }}
{{- else }}
  syncPolicy: {}
{{- end }}
{{- end }}